### ISSUE TITLE
Have a problem to use this tool.

### ISSUE THREAD

**Issue by kanaban** [CalebFenton/dex-oracle#14]
Hi,

I want to execute dex-oracle on my mac.

I entered
dex-oracle /users/aa/bb.apk

It was looks like going well but finally it failed with..

Caused by: java.lang.NullPointerException
	at com.a.b.c.d.app.util.o.aK(PG:416)
	at com.a.b.c.d.app.util.r.o(PG:595)
	at com.a.b.c.d.app.InstallApps.b(PG:3603)
	... 7 more

Optimizations: string_decrypts=24, string_lookups=2, class_lookups=4
/Library/Ruby/Gems/2.0.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:30:in `compile': Crap, smali compilation failed. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:35:in `update_apk'
	from /Library/Ruby/Gems/2.0.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:18:in `finish'
	from /Library/Ruby/Gems/2.0.0/gems/dex-oracle-1.0.5/bin/dex-oracle:96:in `<top (required)>'
	from /usr/local/bin/dex-oracle:23:in `load'
	from /usr/local/bin/dex-oracle:23:in `<main>'

can you help me about this issue?

**Comment by CalebFenton** [comment]
Could you post bb.apk?

**Comment by kanaban** [comment]
post to where?


any other thing is need to launch dex-oracle?

**Comment by CalebFenton** [comment]
Upload it to this github issue or anywhere, or just post the hash.

Once I have that file and your command line arguments, I can reproduce
probably.
