### ISSUE TITLE
a lot of syntax errors

### ISSUE THREAD

**Issue by pwnslinger** [CalebFenton/dex-oracle#2]
Hi caleb!,
during test i got a lot of syntax errors with program

syntax error, unexpected ')', expecting '='

exception errs are :+1: 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugins/unreflector.rb:44: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
  CLASS_LOOKUP_MODIFIER = -> (_, output, out_reg) { "const-...
                              ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugins/unreflector.rb:44: syntax error, unexpected ')', expecting '='
...IFIER = -> (_, output, out_reg) { "const-class #{out_reg}, #...
...                               ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugins/unreflector.rb:44: syntax error, unexpected '}', expecting keyword_end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugin.rb:16:in `block in plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugin.rb:16:in `each'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugin.rb:16:in `plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/dex-oracle/plugin.rb:28:in `init_plugins'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/lib/oracle.rb:11:in `initialize'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/bin/dex-oracle:91:in `new'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.4/bin/dex-oracle:91:in `<top (required)>'
	from /usr/local/bin/dex-oracle:23:in `load'
	from /usr/local/bin/dex-oracle:23:in `<main>'

i'll be thankful if you check the issue.

**Comment by CalebFenton** [comment]
I believe this is because I'm using some ruby 2.x syntax. Try it with ruby 2.x and let me know how it goes.

Sorry for the slow reply. Thought I auto-watched any repos I create.

**Comment by CalebFenton** [comment]
Closing this because I'm pretty sure it's just a ruby 2.x vs ruby 1.x issue. Feel free to re-open if this isn't the case.
