### ISSUE TITLE
did not get warn

### ISSUE THREAD

**Issue by houjingyi233** [CalebFenton/dex-oracle#20]
Hi,in your article Hacking with dex-oracle for Android Malware Deobfuscation,you get warning like:

[WARN] 2017-10-28 12:28:45: Unsuccessful status: failure for Error executing 'static java.lang.String xjmurla.gqscntaej.bfdiays.f.a(int)' with 'I:839889519'
java.lang.reflect.InvocationTargetException

But when I use exactly the same sample and command I cannot get any warning:
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Optimizing 11 methods over 23 Smali files.
Optimizations: 
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Time elapsed 1.782126245 seconds

Any tips?

**Comment by CalebFenton** [comment]
What emulator version are you running and what do the logs say?

**Comment by CalebFenton** [comment]
I'm going to guess that the emulator wasn't running because it looks like nothing executed. Feel free to re-open if you have more details.
