### ISSUE TITLE
Fails when input apk has special characters or space

### ISSUE THREAD

**Issue by mohe2015** [CalebFenton/dex-oracle#24]
```
dex-oracle/bin/dex-oracle xxx\(xxx.apk
sh: 1: Syntax error: "(" unexpected
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::NIL is deprecated
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::Data is deprecated
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::TRUE is deprecated
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::FALSE is deprecated
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::Fixnum is deprecated
/home/moritz/Documents/instagram/dex-oracle/lib/dex-oracle/plugin.rb:21: warning: constant ::Bignum is deprecated
Optimizing 0 methods over 0 Smali files.
Optimizations: 
Time elapsed 6.081287631 seconds

```

**Comment by CalebFenton** [comment]
Back slash is a escape character for your shell and the sequence `\(` is an invalid escape. The error tells you this and it tells you the problem is with your shell.

The `(` character is called parentheses not bracket.

Put the file name in quotes if it has weird characters in it.

**Comment by mohe2015** [comment]
`dex-oracle/bin/dex-oracle -V "xx(x86)(nodpi)xx.apk"` gives me exactly the same error. I think the program uses the shell in a wrong way. If I change 
https://github.com/CalebFenton/dex-oracle/blob/master/lib/dex-oracle/smali_input.rb#L53
```ruby
cmd = "baksmali disassemble --debug-info false --output #{@dir} #{input}"
```
to
```ruby
input = Shellwords.escape(input)
cmd = "baksmali disassemble --debug-info false --output #{@dir} #{input}"
```
like recommended at https://stackoverflow.com/questions/17476389/how-to-escape-strings-for-terminal-in-ruby the program gets over that point but silently fails later, probably because of the same problem. The current program also doesn't work with spaces in the path for me, even if i put the file name in quotes. Can you please verify that?

**Comment by CalebFenton** [comment]
Seems entirely possible. I've updated the issue to reflect full issue.

I must say though this is a low priority fix for me since I consider file names with space or special characters to be something akin to bad hygiene. Fix should be pretty easy though.

**Comment by mohe2015** [comment]
I will close this as I don't think its that important and it pollutes my issues list xD
