### ISSUE TITLE
skipping static constructor methods

### ISSUE THREAD

**Issue by idanr1986** [CalebFenton/dex-oracle#3]
for some reason when dex-oracle iterates over all class and methods and skips over
.method static constructor <clinit>()V 
with all the encrypted strings in this example: 82232590e17bcd612c3871286eb24ac0e22997f42f06ec2b74f29963b5921376

if i change the method sig to .method static a(Ljava/lang/String;)Ljava/lang/String; the string decryption works,

any idea how to make dex-oracle decrypt strings in static constructor methods?

**Comment by CalebFenton** [comment]
Thanks for the bug report. I believe the issue has been fixed in https://github.com/CalebFenton/dex-oracle/commit/2ec4a9fced141e7a8b20c70a6321695fb21b5dc8. Could you test it on your end and let me know how it goes?

**Comment by idanr1986** [comment]
works like a charm thanks man 👍
