### ISSUE TITLE
Connect to emulator on different IP Address

### ISSUE THREAD

**Issue by dazzleworth** [CalebFenton/dex-oracle#34]
Can I specify a different IP address to connect to like

`adb connect 10.71.34.101`

**Comment by strazzere** [comment]
I haven't done this in a while, though you should just need to run that command you've specified, `adb connect host:port` -- then you can pass that as a device serial.

The way adb works, it sort of oddly abstracts the `host:port` to be the device serial. So when using `dex-oracle -s host:port`, the connection should be fine.

**Comment by dazzleworth** [comment]
It works. Although you meant `-d`
