### ISSUE TITLE
dex-oracle on Windows 7 troubleshooting

### ISSUE THREAD

**Issue by Sputuks3** [CalebFenton/dex-oracle#8]
Hello again. I get this when running on Windows. I know where they are located. But how to I get it to point to the right path? (Or how do I manually set the path?)

![image](https://cloud.githubusercontent.com/assets/1269084/17441134/3d49158c-5b62-11e6-9ea1-12c4ac3a9932.png)

**Comment by CalebFenton** [comment]
It should be as simple as setting the path environment variable in Windows and opening a new terminal. If you open start menu and search "Path", there are two options, and one of them says something about environment variables.

Here's the path I used on my test environment:

```
C:\Ruby23-x64\bin;C:\bin;C:\android-sdk\build-tools\24.0.0;C:\android-sdk\platform-tools
```

And `C:\bin` contains the smali and baksmali jars and batch scripts for running them. Here's `C:\bin\smali.bat`:

```batch
@echo off 
java -jar "%~dp0\smali-2.1.2.jar" %* 
```

**Comment by Sputuks3** [comment]
![image](https://cloud.githubusercontent.com/assets/1269084/17443467/62e8d8d0-5b6d-11e6-8760-1d3b4770001e.png)

**Comment by CalebFenton** [comment]
What android version are you running? What happens when you shell into it
and run dalvikvm ?

**Comment by Sputuks3** [comment]
How to check?

**Comment by CalebFenton** [comment]
When you start your emulator, it'll have the version number in the target column.

To shell into it, run `adb shell` in your console. Then execute `dalvikvm` and see what happens.

**Comment by Sputuks3** [comment]
![image](https://cloud.githubusercontent.com/assets/1269084/17541582/7c3e5fa6-5ef3-11e6-91e0-1b563f824d34.png)

Running `dalvikvm` tells me dalvikvm requires a class name

**Comment by CalebFenton** [comment]
You start the emulator, use adb to shell into it (`adb shell`), and run dalvikvm from inside the shell.

Also, if you weren't running the android emulator before, and it kind of looks like you weren't, you need to be running an emulator for dex-oracle to work.

**Comment by Sputuks3** [comment]
![image](https://cloud.githubusercontent.com/assets/1269084/17542162/eb2cb980-5ef8-11e6-85d2-4a7793d12299.png)

`dalvikvm` requires a class name

**Comment by CalebFenton** [comment]
Were you running an android emulator with the first error?

Please give me lots and lots of context and detail and try and answer all
questions. This is an experimental tool and I need to know exactly what
your environment is, the apk or Dex, and the command you used to ran Oracle.

**Comment by Sputuks3** [comment]
Yes. I reproduce the error below again. I'm using Windows 7, and Github for Windows shell for a pseudo-linux environment.  The APK/DEX is the same I provided in a thread in Simplify [here](https://github.com/CalebFenton/simplify/issues/52)

Emulator is at Android 4.0 and API level 14 and armebi-v7a

Emulator is up and running. The full stack trace is below. It seems that transfer to and from device is ok. Just that a certain command is failing.
![image](https://cloud.githubusercontent.com/assets/1269084/17543188/58260fa2-5f01-11e6-9638-b42c222b954a.png)

**Comment by CalebFenton** [comment]
I've been busy with other things but haven't forgotten about this. I'm curious, do you have the latest commits? You can do `git log`, check the top commit, and compare with the one on github. Right now, it's https://github.com/CalebFenton/dex-oracle/commit/2c11fe1b6dc0e6ea98f7a349af03294ec9f75dce.

**Comment by Sputuks3** [comment]
Yes. I have the latest.
