### ISSUE TITLE
the exception:"Failure to merge input DEX and driver DEX: was found

### ISSUE THREAD

**Issue by lelandyang** [CalebFenton/dex-oracle#9]
I encountered such an exception when I was trying to execute:dex-oracle ~/1.apk on ubuntu 15.10
- the following details might help:<br/>
  java version "1.6.0_45"<br/>
  Java(TM) SE Runtime Environment (build 1.6.0_45-b06)<br/>
  Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)<br/>
  adb version:  Android Debug Bridge version 1.0.31
# 

Here is the detailed error:

> wolf@wolf:~$ dex-oracle ~/1.apk
> [ERROR] 2016-09-17 01:53:43: Failure to merge input DEX and driver DEX:
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/merge/DexMerger : Unsupported major.minor version 52.0
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
>     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> Could not find the main class: com.android.dx.merge.DexMerger.  Program will exit.

**Comment by CalebFenton** [comment]
Sorry for the slow reply. Do you have a file hash for the apk you were using?

**Comment by lelandyang** [comment]
I can send you this apk via email if it's convenient to you.

**Comment by CalebFenton** [comment]
Upon actually reading the error, it's clear what the problem is. You need to use Java 8.

All my projects use Java 8 because I'm optimistic, perhaps a little naive and foolhardy, and find an odd pleasure dragging people into the present kicking and screaming!

Please open another issue if dex-oracle breaks for any reason other than Java 8.
